const RECIEVE_ALL_CARS = 'RECIEVE_ALL_CARS';
const RECIEVE_ALL_BRANDS = 'RECIEVE_ALL_BRANDS';
const RECIEVE_ALL_TENANTS = 'RECIEVE_ALL_TENANTS';
const RECIEVE_CARS_ON_TERRITORY = 'RECIEVE_CARS_ON_TERRITORY';
const ADD_NEW_CAR = 'ADD_NEW_CAR';
const ADD_NEW_ENTRY = 'ADD_NEW_ENTRY';
const FAIL_ADDING_CAR = 'FAIL_ADDING_CAR';

export {
  RECIEVE_ALL_CARS,
  RECIEVE_ALL_BRANDS,
  RECIEVE_ALL_TENANTS,
  RECIEVE_CARS_ON_TERRITORY,
  ADD_NEW_CAR,
  ADD_NEW_ENTRY,
  FAIL_ADDING_CAR,
};
