const RECIEVE_ALL_CARS = 'RECIEVE_ALL_CARS';
const ADD_NEW_CAR = 'ADD_NEW_CAR';
const ADD_NEW_ENTRY = 'ADD_NEW_ENTRY';
const FAIL_ADDING_CAR = 'FAIL_ADDING_CAR';

export {RECIEVE_ALL_CARS, ADD_NEW_CAR, ADD_NEW_ENTRY, FAIL_ADDING_CAR};
